// <auto-generated />
using System;
using Doctorly.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Doctorly.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Doctorly.Domain.Entities.Attendee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("CalendarEventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("calendar_event_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("IsAttending")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_attending");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_attendees");

                    b.HasIndex("CalendarEventId")
                        .HasDatabaseName("ix_attendees_calendar_event_id");

                    b.ToTable("attendees", (string)null);
                });

            modelBuilder.Entity("Doctorly.Domain.Entities.CalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("row_version");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_calendar_events");

                    b.ToTable("calendar_events", (string)null);
                });

            modelBuilder.Entity("Doctorly.Domain.Entities.Attendee", b =>
                {
                    b.HasOne("Doctorly.Domain.Entities.CalendarEvent", null)
                        .WithMany("Attendees")
                        .HasForeignKey("CalendarEventId")
                        .HasConstraintName("fk_attendees_calendar_events_calendar_event_id");
                });

            modelBuilder.Entity("Doctorly.Domain.Entities.CalendarEvent", b =>
                {
                    b.OwnsOne("Doctorly.Domain.ValueObjects.TimeRange", "Duration", b1 =>
                        {
                            b1.Property<Guid>("CalendarEventId")
                                .HasColumnType("TEXT")
                                .HasColumnName("id");

                            b1.Property<DateTime>("End")
                                .HasColumnType("TEXT")
                                .HasColumnName("duration_end");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("TEXT")
                                .HasColumnName("duration_start");

                            b1.HasKey("CalendarEventId");

                            b1.ToTable("calendar_events");

                            b1.WithOwner()
                                .HasForeignKey("CalendarEventId")
                                .HasConstraintName("fk_calendar_events_calendar_events_id");
                        });

                    b.Navigation("Duration")
                        .IsRequired();
                });

            modelBuilder.Entity("Doctorly.Domain.Entities.CalendarEvent", b =>
                {
                    b.Navigation("Attendees");
                });
#pragma warning restore 612, 618
        }
    }
}
